DB_SETTINGS:
    host: "cloud.lorawan.internal.aceso.no"
    port: 5432
    user: root
    passwd: "root"
    db: ttn_lorawan_dev

REDIS_SETTINGS:
    cloud_host: "cloud.lorawan.internal.aceso.no"
    edge_host: "client.lorawan.co.ua"
    port: 6379
    db_cloud: 0
    db_replica: 1
    db_devlist: 2
    db_edge: 0
    password:

SELF:
    slot_name: redis_slot
    start_lsn: 0
    only_events: None
    ignored_events:
       - insert
    only_tables:
       - end_devices
    ignored_tables: None
    only_schemas:
       - public
    ignored_schemas: None
    use_add_table_option: True
