version: "3.9"
services:

services:
  pgsql2redis:
    image: pgsql2redis
    command: python3 edge.py edge-config.yaml
    volumes:
      - ${DEV_DATA_DIR:-.env/data}/psql2redis:/data
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - web

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ttn_lorawan_dev
    volumes:
      - ${DEV_DATA_DIR:-.env/data}/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - web

  redis:
    image: redis:6.2.6-bullseye
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - ${DEV_DATA_DIR:-.env/data}/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - web

  stack:
    image: uy0ll/lorawan-stack:3.17.2-stable
    entrypoint: ttn-lw-stack -c /config/ttn-lw-stack-docker.yml
    command: start
    restart: unless-stopped
    depends_on:
      - redis
      - cockroach

    # If using (self) signed certificates:
    secrets:
      - ca.pem
      - cert.pem
      - key.pem
    volumes:
      - ./blob:/srv/ttn-lorawan/public/blob
      - ./config/stack:/config:ro
      # If using Let's Encrypt:
      # - ./acme:/var/lib/acme

    ports:
      # If deploying on a public server:
      #- "80:1885"
      #- "443:8885"
      - "1881:1881"
      - "8881:8881"
      - "1882:1882"
      - "8882:8882"
      - "1883:1883"
      - "8883:8883"
      - "1884:1884"
      - "8884:8884"
      - "1885:1885"
      - "8885:8885"
      - "1886:1886"
      - "8886:8886"
      - "1887:1887"
      - "8887:8887"
      - "1700:1700/udp"
    
    networks:
      - web
      
    environment:
      - TTN_LW_LOG_LEVEL=debug
      - TTN_LW_NS_NET_ID=000000
      #  - TTN_LW_INTEROP_SENDER_CLIENT_CA_DIRECTORY=/config/interopconf/sender-client-ca
      - TTN_LW_NS_INTEROP_DIRECTORY=/config/interopconf
      # If using CockroachDB:
      - TTN_LW_IS_DATABASE_URI=postgres://root@cloud.lorawan.internal.aceso.no:26257/ttn_lorawan?sslmode=disable
      - TTN_LW_REDIS_ADDRESS=redis:6379
      - TTN_LW_BLOB_LOCAL_DIRECTORY=/srv/ttn-lorawan/public/blob

      # Let's Encrypt for "thethings.example.com":
      # - TTN_LW_TLS_SOURCE=acme
      # - TTN_LW_TLS_ACME_DIR=/var/lib/acme
      # - TTN_LW_TLS_ACME_EMAIL=you@thethings.example.com
      # - TTN_LW_TLS_ACME_HOSTS=thethings.example.com
      # - TTN_LW_TLS_ACME_DEFAULT_HOST=thethings.example.com

      # If using (self) signed certificates:
      - TTN_LW_TLS_SOURCE=file
      - TTN_LW_TLS_ROOT_CA=/run/secrets/ca.pem
      - TTN_LW_TLS_CERTIFICATE=/run/secrets/cert.pem
      - TTN_LW_TLS_KEY=/run/secrets/key.pem

      # HTTP Server configuration:
      - TTN_LW_HTTP_COOKIE_HASH_KEY=8cf9756d325721de0dea0f19a37208fba677b926036492218de828e8704af991e07b3349dc9592f5b254bed4f4374f0cf97cd22a91020dac1d0f12de7c97dced
      - TTN_LW_HTTP_COOKIE_BLOCK_KEY=9bb3a2daf648392ab5a4022d3f43787ebeab8307f251b971c41af4591acb9313  # generate 32 bytes (openssl rand -hex 32)
      - TTN_LW_HTTP_METRICS_PASSWORD=metrics # choose a password
      - TTN_LW_HTTP_PPROF_PASSWORD=pprof # choose a password

      # Email configuration for "thethings.example.com":
      # - TTN_LW_IS_EMAIL_SENDER_NAME=AcesoAS-LoRaWAN 
      # - TTN_LW_IS_EMAIL_SENDER_ADDRESS=no_reply_alerts@aceso.no
      # - TTN_LW_IS_EMAIL_NETWORK_CONSOLE_URL=https://edge.lorawan.internal.aceso.no/console
      # - TTN_LW_IS_EMAIL_NETWORK_IDENTITY_SERVER_URL=https://edge.lorawan.internal.aceso.no/oauth

      # If sending email with Sendgrid:
      # - TTN_LW_IS_EMAIL_PROVIDER=sendgrid
      # - TTN_LW_IS_EMAIL_SENDGRID_API_KEY=enter Sendgrid API key

      # If sending email with SMTP:
      # - TTN_LW_IS_EMAIL_PROVIDER=smtp
      # - TTN_LW_IS_EMAIL_SMTP_ADDRESS=no_reply_alerts@aceso.no
      # - TTN_LW_IS_EMAIL_SMTP_USERNAME=no_reply_alerts@aceso.no
      # - TTN_LW_IS_EMAIL_SMTP_PASSWORD=xyz

      # If Application Server enabled, defaults for "thethings.example.com":
      - TTN_LW_AS_MQTT_PUBLIC_ADDRESS=edge.lorawan.internal.aceso.no:1883
      - TTN_LW_AS_MQTT_PUBLIC_TLS_ADDRESS=edge.lorawan.internal.aceso.no:8883

      # If Application Server enabled, Application Server interoperability configuration:
      # If interoperability configuration repository is a directory on OS FS:
      # - TTN_LW_AS_INTEROP_DIRECTORY=/path/to/interop/repository
      # If interoperability configuration repository is a URL:
      # - TTN_LW_AS_INTEROP_URL=https://edge.lorawan.internal.aceso.no
      # If interoperability configuration repository is a blob:
      # - TTN_LW_AS_INTEROP_BLOB_PATH=/path/to/interop/directory
      # - TTN_LW_AS_INTEROP_BLOB_BUCKET=enter bucket name

      # If Gateway Server enabled, defaults for "thethings.example.com":
      # - TTN_LW_GS_MQTT_PUBLIC_ADDRESS=edge.lorawan.internal.aceso.no:1882
      # - TTN_LW_GS_MQTT_PUBLIC_TLS_ADDRESS=edge.lorawan.internal.aceso.no:8882
      # - TTN_LW_GS_MQTT_V2_PUBLIC_ADDRESS=edge.lorawan.internal.aceso.no:1881
      # - TTN_LW_GS_MQTT_V2_PUBLIC_TLS_ADDRESS=edge.lorawan.internal.aceso.no:8881

      # If Gateway Configuration Server enabled, defaults for "thethings.example.com":
      # - TTN_LW_GCS_BASIC_STATION_DEFAULT_LNS_URI=wss://edge.lorawan.internal.aceso.no:8887
      # - TTN_LW_GCS_THE_THINGS_GATEWAY_DEFAULT_MQTT_SERVER=mqtts://edge.lorawan.internal.aceso.no:8881

      # If Network Server enabled, Network Server interoperability configuration:
      # If interoperability configuration repository is a directory on OS FS:
      # - TTN_LW_NS_INTEROP_DIRECTORY="./interopconf"
      # If interoperability configuration repository is a URL:
      # - TTN_LW_NS_INTEROP_URL=https://edge.lorawan.internal.aceso.no
      # If interoperability configuration repository is a blob:
      # - TTN_LW_NS_INTEROP_BLOB_PATH=/path/to/interop/directory
      # - TTN_LW_NS_INTEROP_BLOB_BUCKET=enter bucket name

      # Web UI configuration for "thethings.example.com":
      - TTN_LW_IS_OAUTH_UI_CANONICAL_URL=https://edge.lorawan.internal.aceso.no/oauth
      - TTN_LW_IS_OAUTH_UI_IS_BASE_URL=https://edge.lorawan.internal.aceso.no/api/v3
      - TTN_LW_CONSOLE_OAUTH_AUTHORIZE_URL=https://edge.lorawan.internal.aceso.no/oauth/authorize
      - TTN_LW_CONSOLE_OAUTH_TOKEN_URL=https://edge.lorawan.internal.aceso.no/oauth/token
      - TTN_LW_CONSOLE_UI_CANONICAL_URL=https://edge.lorawan.internal.aceso.no/console
      - TTN_LW_CONSOLE_UI_IS_BASE_URL=https://edge.lorawan.internal.aceso.no/api/v3
      - TTN_LW_CONSOLE_UI_GS_BASE_URL=https://edge.lorawan.internal.aceso.no/api/v3
      - TTN_LW_CONSOLE_UI_NS_BASE_URL=https://edge.lorawan.internal.aceso.no/api/v3
      - TTN_LW_CONSOLE_UI_AS_BASE_URL=https://edge.lorawan.internal.aceso.no/api/v3
      - TTN_LW_CONSOLE_UI_JS_BASE_URL=https://edge.lorawan.internal.aceso.no/api/v3
      - TTN_LW_CONSOLE_UI_EDTC_BASE_URL=https://edge.lorawan.internal.aceso.no/api/v3
      - TTN_LW_CONSOLE_UI_QRG_BASE_URL=https://edge.lorawan.internal.aceso.no/api/v3

      # Console OAuth client and secret:
      - TTN_LW_CONSOLE_OAUTH_CLIENT_ID=console
      - TTN_LW_CONSOLE_OAUTH_CLIENT_SECRET=ee60607d8e8ca7ffe947b9b36ede52a3d4e54a9b28a581b8ef41e3728c2023bc # generate a good one using (openssl rand -hex 32)
    
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:edge.lorawan.internal.aceso.no"
      - "traefik.enable=true"
      - "traefik.port=1885"
      
# If using (self) signed certificates:
secrets:
  ca.pem:
    file: ./ca.pem
  cert.pem:
    file: ./cert.pem
  key.pem:
    file: ./key.pem

networks:
  web:
    external: true
